ARG IMAGE

FROM ${IMAGE}

RUN --mount=type=bind,target=/context \
     miktex --admin --verbose packages update-package-database \
  && (miktex --admin --verbose packages install --package-id-file /context/Packages.list || (cat /var/log/miktex/mpmcli_admin.log && exit 1)) \
  && initexmf --admin --update-fndb
